[project]
name = "mcp-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ikahrilas", email = "ijk60068@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=3.4.7",
    "openai>=3.6.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
mcp-tools = "mcp_tools:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
