[project]
name = "advanced-prompting-patterns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ikahrilas", email = "ijk60068@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "datetime>=6.0",
    "openai>=3.3.1",
    "pydantic>=2.13.4",
    "python-dotenv>=1.2.3",
    "tiktoken>=0.14.0",
]

[project.scripts]
advanced-prompting-patterns = "advanced_prompting_patterns:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
